// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiahyspsvgfvyvgoffwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppYWh5c3Bzdmdmdnl2Z29mZndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTU5ODQsImV4cCI6MjA3MTU3MTk4NH0._IkqZG94CigJtcO_EjeN_kymkGGSxzvBQVPgaqae5eQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});