// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbncvdntwverdchsamtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibmN2ZG50d3ZlcmRjaHNhbXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTU5MjMsImV4cCI6MjA3MTU3MTkyM30.YHGDO2SEj2fkBO8W6jOibaJVi2t3Rr8ZtoJ9tLp2vuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});